apiVersion: v1
kind: Service
metadata:
  name: user-internal
  namespace: user
spec:
  type: ClusterIP
  selector:
    app: user-internal
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081